### ISSUE TITLE
Can't integrate with TravisCI without write permissions

### ISSUE THREAD

**Issue by seagreen** [seagreen/hjsonschema#14]
@mdorman Do you mind if I remove the TravisCI integration file? It would have been great to have it, but it wants write permissions and that's a no-go.

P.S. Thanks for knocking out the automated test setup.

**Comment by mdorman** [comment]
Yeah, sure.

**Comment by seagreen** [comment]
Thanks. I hope it's OK that I removed the `description` as well, I'm on a no-description revolt until https://github.com/haskell/hackage-server/issues/262 goes through.

I pushed the new version to Hackage, so it you need to be able to pull a version of hjsonschema that includes your permissive lower bounds you're all set.

PS Welcome to the exciting world of Haskell JSON Schemas:)
