### ISSUE TITLE
Consider switching to a different regex library

### ISSUE THREAD

**Issue by dylex** [seagreen/hjsonschema#17]
The current one, regexpr, is rather old and somewhat broken.  Recently ran across a schema we use containing a valid regex it rejected (`parse error: regex "^[+-]?([0-9]+:){0,2}[0-9]+(\\.[0-9]*)?$" is uncorrect`).  I'd file a bug with it but it doesn't seem to be maintained.

**Comment by seagreen** [comment]
Does anyone have suggestions for a better regex lib? The [JSON Schema spec](http://json-schema.org/latest/json-schema-validation.html#anchor33) requires that it use the ECMA 262 regular expression dialect.

**Comment by dylex** [comment]
`regex-pcre`, `regex-pcre-builtin` or one of their derivitives should be pretty close. It looks like some of the other json schema libraries contrive to call out to an actual js engine to do the regex handling.

**Comment by seagreen** [comment]
Thanks for the advice. Sorry I'm getting to this so slowly.

Going by the list of reverse dependencies (http://packdeps.haskellers.com/reverse) some of the other regex libraries seem to be much more commonly used than regex-pcre. Do you have a reason for suggesting it over something like regex-posix?

**Comment by dylex** [comment]
Only that ECMA 262 regexps are much closer to perl's than posix (posix regexs are missing some features, though in practice it's probably not that important).  Many of them use the same standard `regex-base` interface.

**Comment by seagreen** [comment]
Unfortunately the `regex-pcre` libraries run in `IO`: https://hackage.haskell.org/package/regex-pcre-builtin-0.94.4.8.8.35/docs/Text-Regex-PCRE-String.html. That knocks them out of consideration, as I don't know near enough haskell to try `unsafePerformIO` or anything like that.

If you decide to use your own regex code locally you can. It requires building your own `Spec`. Unfortunately you not only need to replace the "pattern" validator (here: https://github.com/seagreen/hjsonschema/blob/master/src/Data/JsonSchema.hs#L37), but also "patternProperties" which uses regexes, and "properties" which depends on "patternProperties". Be warned: the properties related code is _extremely_ ugly, I just did enough to get it compiling and moved on.

Even though I don't see a simple solution this is definitely a real problem, so I'm going to leave this open for now.

**Comment by seagreen** [comment]
Going to try [pcre-heavy](https://github.com/myfreeweb/pcre-heavy) for this.

**Comment by seagreen** [comment]
Done! https://github.com/seagreen/hjsonschema/commit/cd19d797eea968107a980b42bc1422b8c7c1ca07
