### ISSUE TITLE
Improving error reporting?

### ISSUE THREAD

**Issue by yrashk** [seagreen/hjsonschema#18]
Right now hjsonschema would dump the Aeson structures into the error's Text. Have you considered switching this to `encode`/`encodePretty` so that the error would contain something actually readable; or, as an option, improving the error data type to carry the actual offending data structure. I'd be happy to help or contribute if this is something you're willing to consider.

**Comment by seagreen** [comment]
That sounds good to me. What type signature were you thinking to replace `ValErr`? Right now it's just `type ValErr = Text`.

It could change to something like `data ValErr = ValErr Text (Maybe Value)` if we wanted to keep things simple.

Another option would be to have a real error sum type. This would be a lot more work to implement though, and I don't want to do it until I've got a plan to get it right.

**Comment by yrashk** [comment]
I was thinking something along the lines of

```
data ValErr a = ValErr { description: Text, offender: (Maybe Value), descriptionArguments :: [a]  }
```

the motivation for arguments would be to pass printf-like string into description. This way it can be easily rendered (`Text.Printf.printf`) or all the arguments can be extracted and rendered however the end user wants them to be rendered, while still preserving the correct error message. What do you think?

**Comment by yrashk** [comment]
But if this is too much to ask for, `data ValErr = ValErr Text (Maybe Value)` will be WAY better than what's there right now :)

**Comment by seagreen** [comment]
Could you give me an example of how `descriptionArguments` would be combined with printf? That would help me understand.

**Comment by yrashk** [comment]
You are right, using `printf` in such fashion won't be trivial. Can we do `data ValErr = ValErr Text (Maybe Value)` then, at least?

**Comment by seagreen** [comment]
Sounds great. I may have time to get to it this week. If you start on it first let me know, I'll do the same.

**Comment by seagreen** [comment]
Going to start playing with it tonight.

**Comment by seagreen** [comment]
It's coming along. I've now got a nice sum type to describe errors: https://github.com/seagreen/hjsonschema/pull/20/files#diff-b5268386737609e0e67ac5104f346864R44

The trick is that I don't want individual validators to know about it. That would prevent them being used in a mix-and match fashion without encouraging partial functions.

For example, if someone writes their own `Spec` that only includes the `minimumLength` and `maximumLength` validators, they should be able to use the type system to enforce that those are the only errors that can actually be returned.

Anyway, the the new code needs a fair amount of cleanup. When that's done and it's in an easy-to-read state I'll post a notice here and ask for more comments.

**Comment by seagreen** [comment]
This should take care of it. Here's the new general error type: https://github.com/seagreen/hjsonschema/blob/master/src/Data/JsonSchema/Core.hs#L73

And here's the sum type of actual errors that can happen when using the JSON Schema Draft4 `Spec` provided with the library: https://github.com/seagreen/hjsonschema/blob/master/src/Data/JsonSchema/Draft4.hs#L18

They're an example of examining the new error type in the example code: https://github.com/seagreen/hjsonschema/blob/master/Example.hs#L60

**Comment by seagreen** [comment]
PS Definitely let me know if you have more questions or suggestions. And thanks for the suggestions thus far!
