### ISSUE TITLE
Test that the package will still work after being uploaded to Hackage

### ISSUE THREAD

**Issue by seagreen** [seagreen/hjsonschema#35]
This is to prevent issues [like this](https://github.com/seagreen/hjsonschema/pull/34) where tests pass during development even though there are missing `extra-source-files`, but don't pass for people downloading the package from Hackage.

Two solutions: either `stack test` can be changed to only see what would be on the filesystem after a Hackage upload/download, or the TravisCI run can be changed to do so.

**Comment by seagreen** [comment]
@mdorman want to look into getting multi-ghc-travis template changed and I'll look into the `stack test` option?

**Comment by mdorman** [comment]
I can't make any promises about how quickly I'll be able to get to it, but I will be happy to look into it---I think it could be an improvement that would probably benefit a lot of projects.

**Comment by seagreen** [comment]
Good news, the stack people are already working on it here: https://github.com/commercialhaskell/stack/issues/717

So don't feel like you need to open the multi-ghc-travis issue for hjsonschema's sake, though of course helping the community's always good.

**Comment by seagreen** [comment]
In the short run if anyone knows how to modify `.travis.yml` to test that `cabal test` works for the sdist that would be awesome.

**Comment by seagreen** [comment]
Note: include testing Haddocks.

**Comment by hvr** [comment]
@seagreen btw, want to give https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs a try? it generates an sdist, and unpacks it, and then performs builds & tests from within the unpacked source-tarball. And there's experimental support for testing against LTS snapshots.

**Comment by seagreen** [comment]
@hvr: Looks great, just switched to it in 445f47746baee10c6d16bf93b55b7bf082afb3d6.

It would be even better if it tested Haddocks (I'll open an issue about this), but it's already super nice. `extra-source-modules` and `other-modules` were by far my most common places to make mistakes.
