### ISSUE TITLE
Add hjsonschema to stackage

### ISSUE THREAD

**Issue by dredozubov** [seagreen/hjsonschema#36]
Pretty please?

**Comment by seagreen** [comment]
Good idea, will report back soon.

**Comment by seagreen** [comment]
Started, that was easy so far:

https://github.com/fpco/stackage/compare/master...seagreen:patch-1

**Comment by seagreen** [comment]
I lied, now it's started: https://github.com/fpco/stackage/pull/1482

**Comment by seagreen** [comment]
Done!

**Comment by dredozubov** [comment]
great, thanks!
