### ISSUE TITLE
hjsonschema-0.1.0.0 fails test suite (because of missing files?)

### ISSUE THREAD

**Issue by peti** [seagreen/hjsonschema#4]
Citing from http://hydra.cryp.to/build/527182/nixlog/2/raw:

```
Linking dist/build/official/official ...
running tests
Running 1 test suites...
Test suite official: RUNNING...
official: JSON-Schema-Test-Suite/tests/draft4: getDirectoryContents: does not exist (No such file or directory)
Test suite official: FAIL
```

**Comment by seagreen** [comment]
That was a silly mistake by me, but easily fixed.

Hydra's going to have another problem though with this part though -- running tests requires manual commands.

```
# Run Tests

    cd JSON-Schema-Test-Suite/remotes
    python -m SimpleHTTPServer 1234
```

If I rewrite the test suite to fire up a local server on port `1234` programmatically, will that work on Hydra or will that not be allowed?

**Comment by peti** [comment]
I'm not sure, to be honest. Binding to local ports should work fine, but that kind of test suite is going to be subject to race conditions whenever we've running more than one of these builds at the same time.

**Comment by seagreen** [comment]
Thanks for the info! Sounds like I need to break the tests into two suites.

**Comment by peti** [comment]
That would be perfect, yes!

**Comment by seagreen** [comment]
You can now run all the tests that need no setup with `cabal test local`. If that doesn't take care of the problem definitely let me know. Thanks very much for the help.

**Comment by peti** [comment]
Awesome, thank you very much for your efforts.
