### ISSUE TITLE
Support for title and description.

### ISSUE THREAD

**Issue by pheaver** [seagreen/hjsonschema#44]
Title and description aren't supported in hjsonschema now, I assume because they have no meaning in validation and can be discarded. But if anyone wants to generate JSON from an hjsonschema `Schema` (I do!), then they're going to want to be able to set the title and description.

This could be accomplished with explicit title and description fields in `Schema` or arbitrary name-json pairs at the top-level.

It could also be useful to capture all unrecognized top-level name-json pairs in the parsed `Schema`.

**Comment by seagreen** [comment]
This is a great idea! Implementing it brings up some questions though...

> It could also be useful to capture all unrecognized top-level name-json pairs in the parsed Schema.

This is actually done! See here: https://github.com/seagreen/hjsonschema/blob/master/src/JSONSchema/Draft4/Schema.hs#L23

I wonder if I've made the wrong decision to do it this way though. In my head I see some kind of progression from:

```
minimal schema for validation (eg not distinguishing between `"type": "string"` and `"type": ["string"]`
->
schema that reproduces everything related to validation exactly, but nothing else
->
schema that includes everything the spec mentions not related to validation, like `"title"` and `"description"`.
->
a newtype for a JSON Value that's also supposed to be a schema, that way it can include any arbitrary key
```
I need to try to write this out in the library and see if it works.

In the meantime is `_schemaOther` enough to take care of your needs?

**Comment by pheaver** [comment]
Ah, yes, `_schemaOther` does work, thanks!
