### ISSUE TITLE
Stackage nightly build failure

### ISSUE THREAD

**Issue by decentral1se** [seagreen/hjsonschema#48]
```
src/JSONSchema/Validator/Draft4/Any.hs:133:5: error:
    parse error on input <E2><80><98>deriving<E2><80><99>
```

**Comment by seagreen** [comment]
It was a Haddock problem, it should be fixed in `1.6.1` (on Hackage).

**Comment by decentral1se** [comment]
Thanks! It's back in the build, let's see!

**Comment by seagreen** [comment]
Sounds good, let me know if there are any more problems. And thanks for finding this one.:heart:
