### ISSUE TITLE
Confusion regarding nested errors

### ISSUE THREAD

**Issue by creichert** [seagreen/hjsonschema#49]
I'm using `hjsonschema` to validate schemas and I have a question regarding detailed error messages:

In previous versions of this library, validation failures carried a JSON pointer to the exact value that failed. This was useful because I could generate exact error messages to deeply nested validation errors: https://github.com/seagreen/hjsonschema/blob/eb2014465f672ad41d6279ec2637c269e6a9fdd2/examples/PrettyShowFailure.hs#L25

As i'm working through `ValidatorFailure` in a more recent version, I noticed this same information was not present, so when I have a deeply nested structure it's more difficult to render an exact pointer to what fails. I did notice [in the changelog](https://github.com/seagreen/hjsonschema/blob/master/changelog.md#1300) there is a mention of making changes to the structure.

Questions:

- Does `FailurePropertiesRelated` indicate a "nested" validation failure which makes it possible to derive the full path to the field which fails?

- Does the validator "keep going" when it encounters failures, if it can? 
  - > Now we return a tree of failure messages, so that if the first schema had only three validators, then no more than three top level failures will be returned.

- Can you shed some light on how to maintain good "pointers" to deeply nested validation failures? 

- Are there any best practices (or external docs) for rendering the errors in a pretty way?

I can provide some more helpful examples, if needed. Thanks!

**Comment by creichert** [comment]
Looking a little further into this, I do see `PropertiesRelatedInvalid` seems to have the correct information in a tree:

```
FailurePropertiesRelated (
    PropertiesRelatedInvalid {
        _prInvalidProperties = fromList [
             ("nested", [
                 FailurePropertiesRelated
                     (PropertiesRelatedInvalid {
                        _prInvalidProperties = fromList [
                           ("nested_number",[
                               FailureMultipleOf (MultipleOfInvalid (MultipleOf {_unMultipleOf = 7.0}) 1600.0)])
                        ]
                      , _prInvalidPattern = fromList []
                      , _prInvalidAdditional = Nothing
                      })
              ])
              , ("number",[])
          ]
        , _prInvalidPattern = fromList []
        , _prInvalidAdditional = Nothing
        }) :| []
```

That makes sense, I think I just need to accumulate these keys and build a path for the validation error.

**Comment by seagreen** [comment]
> That makes sense, I think I just need to accumulate these keys and build a path for the validation error.

This is definitely how it's supposed to work. Of course, the fact that you had to dig around to figure this out is a sign I need to write better docs...

> Does the validator "keep going" when it encounters failures, if it can?

Yep, it will report every error!

> Are there any best practices (or external docs) for rendering the errors in a pretty way?

Sadly, no. Pretty error rendering with a `[ValidatorFailure] -> Text` function is definitely within the scope of this project, I just haven't gotten around to it.

Do you have what you need to make progress? If you see any error results that look strange feel free to let me know. Since the contents of errors aren't thoroughly tested this is probably the most likely place for the library to have defects.

**Comment by creichert** [comment]
@seagreen Thanks a lot! I do have what I need. 

I'll work through it and hopefully have something to contribute. I'll open more specific issues if I encounter anything weird.
