### ISSUE TITLE
hjsonschema-0.1.0.0 syntax error in Haddock comments

### ISSUE THREAD

**Issue by peti** [seagreen/hjsonschema#5]
Citing from http://hydra.cryp.to/build/532842/log/raw:

```
Running Haddock for hjsonschema-0.1.0.0...
Running hscolour for hjsonschema-0.1.0.0...
Preprocessing library hjsonschema-0.1.0.0...
Preprocessing library hjsonschema-0.1.0.0...

src/Data/JsonSchema/JsonReference.hs:5:1:
    parse error on input ‘import’
```

I suppose that comment would have to be before the `module` statement.

**Comment by seagreen** [comment]
Thanks! Comments should be fixed, I'll close this issue once they show up on Hackage for the new version of the lib: https://hackage.haskell.org/package/hjsonschema-0.1.1.0

**Comment by peti** [comment]
The build works fine now: http://hydra.cryp.to/build/537017. Thank you very much for your effors!
