### ISSUE TITLE
Why is exclusive minimum/maximum fields bool in this library?

### ISSUE THREAD

**Issue by sras** [seagreen/hjsonschema#53]
According to the [spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.7.2), it seems that they should really be numbers. Why this difference?

**Comment by seagreen** [comment]
You're looking at a newer version of the spec, Draft 4 exclusiveMaximim / exclusiveMinimum are bools. This is an easy mistake to make, the specs don't do a great job of making their version clear.
