### ISSUE TITLE
Consider undeprecating

### ISSUE THREAD

**Issue by creichert** [seagreen/hjsonschema#61]
I do understand your motives for deprecation and I don't disagree with them in general.

hjsonschema is really the only Haskell option for JSON Schema Draft 4. Additionally, there aren't many big holes in this implementation that I've encountered using hjsonschema from Assertible to test many APIs.

I'm not sure there's much else to add but I've added myself as a Watcher on this repo so I can help reduce the maintenance burden if anything pops up.

I'm not suggesting you open indicate that you are developing new code for hjsonschema, but maybe a less jarring notice than full deprecation could be reached. I'm mainly interested that newcomers to this package know it's usable and full-featured but there will not be any new development from _you_.

Thanks for all your work on this package.

**Comment by creichert** [comment]
You can close this btw, just want to make sure you see it :+1:

**Comment by seagreen** [comment]
On one hand it was almost no work to keep `hjsonschema` maintained.

On the other neither JSON Schema nor this implementation excite me anymore (and I'm not planning to use either for personal use again).

So the "deprecated" notice saves me a nice half-cup of mental energy by avoiding implied responsibility.

That said . . . :smiley: . . . if a respected Haskeller came along and wanted to take it over I would be %100 down.

**Comment by creichert** [comment]
Thanks Ian, I understand. I'm not opposed to maintaining the package and
am familiar with the source code. But considering I haven't made any
patches yet why don't we just leave the repo as-is and see if anything
pops up from here. I'm watching the repo and will be sure to keep my eye
on any problems.

**Comment by seagreen** [comment]
Sounds good!
