### ISSUE TITLE
Lift Aeson upper bound

### ISSUE THREAD

**Issue by koterpillar** [seagreen/hjsonschema#62]
This package no longer builds with LTS 13 due to the Aeson `<1.3` requirement. Would be nice to get it into the LTS or at least make it compatible.

**Comment by koterpillar** [comment]
There are no upper bounds in the Cabal file on GitHub, but the bound is present on Hackage.

**Comment by seagreen** [comment]
Thanks! I published a new revision raising the `aeson` bound: http://hackage.haskell.org/package/hjsonschema-1.9.0/revisions/
